[project]
name = "HazardWire"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "deexor64",email = "191124667+deexor64@users.noreply.github.com"},
]
dependencies = ["supabase>=2.31.0", "python-dotenv>=1.2.3", "google-genai>=2.20.0", "numpy>=2.5.2", "opencv-python-headless<5,>=4.10", "fastapi>=0.141.1", "uvicorn>=0.52.4"]
requires-python = "==3.12.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false


[tool.pdm.scripts]
start = "python3 -m src.main"
